version: "3.7"

services:
  db:
    image: postgres:latest
    env_file: envs/dev.env
    ports:
      - 5432:5432
    volumes:
      - pgdata2:/var/lib/postgresql/data

  django_app:
    build: .
    ports:
      - 8005:8001
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8001'
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'
    entrypoint: ./entrypoint.sh
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    env_file: envs/dev.env
    depends_on:
      - db
volumes:
  pgdata2:
    external: true
